trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'YourAzureSubscription'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az group create --name MyResourceGroup --location eastus
      az deployment group create --resource-group MyResourceGroup --template-file main.bicep
  displayName: 'Deploy Infrastructure to Azure'
  
- task: AzureWebApp@1
  inputs:
    appName: 'your-web-app-name'
    package: '$(System.DefaultWorkingDirectory)/drop/your-app.zip'
  displayName: 'Deploy Application to Azure App Service'
